### ISSUE TITLE
question about the final output

### ISSUE THREAD

**Issue by 652994331** [saurabhkulkarni77/DistillBERT#1]
Hi, nice job, can I ask the is the final output of this work a distill bert model ? Can we train a bert distill model through this project? thanks

**Comment by saurabhkulkarni77** [comment]
Yes, you can train Bert distill with this project, I will soon update the readme on how to do it with GCP's TPU

**Comment by 652994331** [comment]
thanks for the reply, btw, is there any  way we can get the finished distill bert?

**Comment by saurabhkulkarni77** [comment]
Currently, it's in my Google Cloud Storage (not public), I will make it public soon.

**Comment by 652994331** [comment]
@saurabhkulkarni77  thanks so much. actually there is a problem i am not sure. according to my understanding,  we need to use teacher's output to train student model, why we choose wiki data? teacher's output is an output of predict or something else?
